export const meals = [
  {
    name: "Zone Breakfast Plate",
    description:
      "2 eggs, 1 slice whole wheat toast, 1/2 apple, 1 oz cheese, 1 tbsp avocado",
    proteinBlocks: 3,
    carbBlocks: 3,
    fatBlocks: 3,
    mealType: "breakfast",
    totalBlocks: 3,
    macros: {
      proteinGrams: 21,
      carbGrams: 27,
      fatGrams: 9,
    },
  },
  {
    name: "Turkey Avocado Salad",
    description:
      "Grilled turkey breast, mixed greens, olive oil, and chickpeas",
    proteinBlocks: 4,
    carbBlocks: 4,
    fatBlocks: 4,
    mealType: "lunch",
    totalBlocks: 4,
    macros: {
      proteinGrams: 28,
      carbGrams: 36,
      fatGrams: 12,
    },
  },
  {
    name: "Salmon with Veggies",
    description: "Grilled salmon with roasted zucchini, olive oil and quinoa",
    proteinBlocks: 4,
    carbBlocks: 4,
    fatBlocks: 4,
    mealType: "dinner",
    totalBlocks: 4,
    macros: {
      proteinGrams: 28,
      carbGrams: 36,
      fatGrams: 12,
    },
  },
  {
    name: "Greek Yogurt Snack",
    description: "Low-fat Greek yogurt with almonds and blueberries",
    proteinBlocks: 2,
    carbBlocks: 2,
    fatBlocks: 2,
    mealType: "snack",
    totalBlocks: 2,
    macros: {
      proteinGrams: 14,
      carbGrams: 18,
      fatGrams: 6,
    },
  },
  {
    name: "Egg White Omelet",
    description: "Egg whites with spinach, mushrooms, and olive oil",
    proteinBlocks: 3,
    carbBlocks: 3,
    fatBlocks: 3,
    mealType: "breakfast",
    totalBlocks: 3,
    macros: {
      proteinGrams: 21,
      carbGrams: 27,
      fatGrams: 9,
    },
  },
  {
    name: "Chicken Stir Fry",
    description:
      "Grilled chicken breast with broccoli, carrots, and sesame oil",
    proteinBlocks: 3,
    carbBlocks: 3,
    fatBlocks: 3,
    mealType: "lunch",
    totalBlocks: 3,
    macros: {
      proteinGrams: 21,
      carbGrams: 27,
      fatGrams: 9,
    },
  },
  {
    name: "Tuna & Apple Snack",
    description: "Tuna with apple slices and a few cashews",
    proteinBlocks: 1,
    carbBlocks: 1,
    fatBlocks: 1,
    mealType: "snack",
    totalBlocks: 1,
    macros: {
      proteinGrams: 7,
      carbGrams: 9,
      fatGrams: 3,
    },
  },
  {
    name: "Zone Chicken Plate",
    description:
      "3 oz grilled chicken breast, 1 cup broccoli, 1/2 cup black beans, 9 cashews",
    proteinBlocks: 3,
    carbBlocks: 3,
    fatBlocks: 3,
    mealType: "lunch",
    totalBlocks: 3,
    macros: {
      proteinGrams: 21,
      carbGrams: 27,
      fatGrams: 9,
    },
  },
  {
    name: "Tofu Veggie Bowl",
    description:
      "Tofu cubes, bell peppers, zucchini, olive oil, and brown rice",
    proteinBlocks: 3,
    carbBlocks: 3,
    fatBlocks: 3,
    mealType: "dinner",
    totalBlocks: 3,
    macros: {
      proteinGrams: 21,
      carbGrams: 27,
      fatGrams: 9,
    },
  },
  {
    name: "Protein Shake Snack",
    description: "Whey protein shake with strawberries and almond butter",
    proteinBlocks: 2,
    carbBlocks: 2,
    fatBlocks: 2,
    mealType: "snack",
    totalBlocks: 2,
    macros: {
      proteinGrams: 14,
      carbGrams: 18,
      fatGrams: 6,
    },
  },
  {
    name: "Zone Tuna Salad",
    description: "Tuna, mixed greens, chickpeas, olive oil, and carrots",
    proteinBlocks: 3,
    carbBlocks: 3,
    fatBlocks: 3,
    mealType: "lunch",
    totalBlocks: 3,
    macros: {
      proteinGrams: 21,
      carbGrams: 27,
      fatGrams: 9,
    },
  },
];
